version: '3.8'

services:
  express:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mean_angular_express
    ports:
      - "3000:3000"
    environment:
      - SECRET=Thisismysecret
      - MONGO_DB_USERNAME=admin-user
      - MONGO_DB_PASSWORD=admin-password
      - MONGO_DB_HOST=database
      - MONGO_DB_PORT=27017
      - MONGO_DB_DATABASE=mean-football
    depends_on:
      - database
    networks:
      - mean-network

  database:
    image: mongo:latest
    container_name: mean_mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin-user
      - MONGO_INITDB_ROOT_PASSWORD=admin-password
    volumes:
      - ./mongo:/home/mongodb
      - ./mongo/init-db.d/:/docker-entrypoint-initdb.d/
      - ./mongo/db:/data/db
    ports:
      - "27017:27017"
    networks:
      - mean-network

networks:
  mean-network:
    driver: bridge
